//------------------------------------------------------------------------------
// <auto-generated>
//     Työkalu muodosti tämän koodin.
//     Suorituksenaikainen versio:4.0.30319.34209
//
//     Tähän tiedostoon tehdyt muutokset saattavat aiheuttaa virheellistä toimintaa. Ne menetetään, jos
//     koodi muodostetaan uudelleen.
// </auto-generated>
//------------------------------------------------------------------------------
#if !EXCLUDE_CODEGEN
#pragma warning disable 162
#pragma warning disable 219
#pragma warning disable 693
#pragma warning disable 1591
#pragma warning disable 1998

namespace OrleansR.Grains
{
    using Orleans.CodeGeneration;
    using Orleans;
    using System;
    using System.Runtime.InteropServices;
    using System.Runtime.Serialization;
    
}
#pragma warning restore 162
#pragma warning restore 219
#pragma warning restore 693
#pragma warning restore 1591
#pragma warning restore 1998
#endif
